### ISSUE TITLE
Alpha/Mask Pixel Modes Not working in for SPRITE_MODE::SINGLE

### ISSUE THREAD

**Issue by 0xnicholasc** [matt-hayward/olcPGEX_AnimatedSprite#3] opened 2020-01-31 01:43 UTC
When I try to use a sprite sheet in SPRITE_MODE::SINGLE, transparent pixels draw as black, even though PIXEL_MODE::MASK is set. The behavior is the same with PIXEL_MODE::ALPHA.

It works in SPRITE_MODE::ALPHA.

I assume it has something to do with the usage of DrawPartialSprite, but have not figured it out yet.

**Comment by matt-hayward** [comment] 2020-01-31 23:11
I'll take a look into this; I don't think I've noticed any issues, though.

**Comment by 0xnicholasc** [comment] 2020-01-31 23:15
I'll double-check to make sure I didn't break it.

**Comment by matt-hayward** [comment] 2020-01-31 23:52
Okay, I've confirmed this issue. It's being caused by calling `pge->SetDrawTarget` on line 221 of the header file.

I'm not sure yet whether it's an issue with this extension or the PGE itself. I'll investigate further.

**Comment by matt-hayward** [comment] 2020-02-01 01:47
I've managed to fathom a fix for this issue, but it seems weird. I'll speak with Javidx9 about it before making a PR in case I've missed something really simple.

**Closed as completed** 2020-02-02 00:53 UTC
Labels: bug
